services:
- postgresql
before_install:
- gem install -v 1.17.3 bundler
before_script:
- psql -c 'create database pgapp_test;' -U postgres
script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
language: ruby
rvm:
- 2.5.0
notifications:
  email:
  - team.snazzyy@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: ikqg5G3MW7HOPb8gnALru/wSZhmU4pj+g4LuarlsRjE+0Unk5wYH0M2DZXierDKlJaDCu6cxLcmQqD/NO4fBO1e4EuuwD9Iz2aY8Jt1FDkLDBjsRkg8Q/WdJNCb7vxgSKuZREi+/uL3O0JTyj8vTAJS3Pg2mLkJA7YJbefccfBDGG5AWzTz+ZiPk5yCpSEI0S3OpHS3yFE7zCgADzoluUjyW0jnoGCT61i1nvC/kAJ2iv0rAOKRXflwGaov+byPYp/s1ntaI6BR3poqsCgDCSqFa7YRxVbQqbRsAJXPZBtbKegf2KqIN/6+XqXGi3C8NOtnN6u3P01DX6QFbJk8aon2u49D5ncJM9ei/8wPq48Z51Wn3INpkeUEiZn+tJaDzXnTg/K8rk0rRM769H2LmKnWCPbdFhDNdns82allDhXjygYCXxv/To1eL78KcSIAWcy9drDRBO7Kx5mv9QZoiL6mvFwwtVvqdmwJtfRsh/Z3XdCyOWS6KfC6TjpJPNEFFOPQZDUWPaxgc01fNOt9Xy5ikAYczcJCgq7X42JEEZdF7NJQ1Qty8OX6EIuVgh03V2miUr/Gru/g9gDO7Lvt/DdABO6Er2/naQmkwNEnJKY5tCsFDqKsCE/v6vulZyU2HCS7QQyI+WP0Od7yd6F0GHe9biRH4JxoqbgyV666vCfw=
