before_install:
 — gem install bundler --version 1.17.3
 — bundle _1.17.3_ install --jobs=3 --retry=3


before_script:
 — psql -c 'create database pgapp_test;' -U postgres

script:
 — bundle install - jobs=3 - retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

language: ruby
rvm:
 — 2.5.0

services:
 — postgresql


