before_install:
  - gem install -v 1.17.3 bundler
  - bundle _1.17.3_ install

script:
  - bundle install - jobs=3 - retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
  
language: ruby
rvm:
 — 2.5.0


